"""notification table updated

Revision ID: 82d34b0cfca4
Revises: 1028ece6ec25
Create Date: 2020-11-12 18:15:44.427603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d34b0cfca4'
down_revision = '1028ece6ec25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'post_id')
    # ### end Alembic commands ###
