"""updated relationship table with a action user id column

Revision ID: 9ef8b0d7e225
Revises: 24d19aea28bb
Create Date: 2020-11-13 23:31:34.163850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef8b0d7e225'
down_revision = '24d19aea28bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('action_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'relationships', 'users', ['action_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_column('relationships', 'action_user_id')
    # ### end Alembic commands ###
